const DB_NAME = 'starlight-spin-db';
const STORE = 'app';
const $ = (id) => document.getElementById(id);
const state = { slots: [], rounds: 5, rotation: 0, spinning: false, muted: false, selectedSlot: 0 };
let audioContext;
function openDb() { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function loadState() { const db = await openDb(); return new Promise((resolve, reject) => { const request = db.transaction(STORE).objectStore(STORE).get('state'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function saveState() { const db = await openDb(); db.transaction(STORE, 'readwrite').objectStore(STORE).put({ slots: state.slots, rounds: state.rounds, muted: state.muted }, 'state'); }
function newSlot(slot) { return { id: slot?.id || crypto.randomUUID(), image: slot?.image || '', name: slot?.name || '' }; }
function filledCount() { return state.slots.filter((slot) => slot.image).length; }
function ready() { return filledCount() === state.slots.length; }
function escapeHtml(value) { return value.replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function render() {
  const count = state.slots.length; const angle = 360 / count; const colors = ['#ff8a9d', '#ffc85b', '#73d7c6', '#93b9ff', '#c69cff', '#ff9cd8'];
  $('slotCount').value = count; $('slotCountValue').textContent = count; $('slotCountLabel').textContent = `${count} ช่อง`; $('filledStatus').textContent = `${filledCount()}/${count}`; $('countPill').textContent = `${filledCount()}/${count}`; $('filledStatus').classList.toggle('ready-text', ready()); $('spinButton').disabled = !ready() || state.spinning; $('clearButton').disabled = filledCount() === 0 || state.spinning;
  $('wheelHint').textContent = state.spinning ? 'ดวงดาวกำลังเลือก...' : ready() ? 'พร้อมแล้ว กดหมุนได้เลย' : 'เพิ่มภาพให้ครบทุกช่องก่อนเริ่ม'; $('helperText').textContent = ready() ? '' : `อัปโหลดภาพอีก ${count - filledCount()} ช่อง เพื่อปลดล็อกวงล้อ`; $('wheel').style.background = `conic-gradient(${state.slots.map((_, index) => `${colors[index % colors.length]} ${index * angle}deg ${(index + 1) * angle}deg`).join(', ')})`; $('wheel').style.transform = `rotate(${state.rotation}deg)`;
  $('wheel').querySelectorAll('.wheel-slot').forEach((node) => node.remove()); state.slots.forEach((slot, index) => { const degrees = index * angle + angle / 2 - 90; const radians = degrees * Math.PI / 180; const radius = count > 12 ? 35 : 37; const node = document.createElement('div'); node.className = 'wheel-slot'; node.style.left = `${50 + Math.cos(radians) * radius}%`; node.style.top = `${50 + Math.sin(radians) * radius}%`; node.innerHTML = slot.image ? `<img src="${slot.image}" alt="${escapeHtml(slot.name || `ตัวละครช่องที่ ${index + 1}`)}">` : `<span class="empty-slot">${index + 1}</span>`; $('wheel').appendChild(node); });
  $('characterList').innerHTML = state.slots.map((slot, index) => `<div class="character-row ${slot.image ? 'has-image' : ''}"><button class="avatar-button" data-upload="${index}">${slot.image ? `<img src="${slot.image}" alt="">` : '＋'}</button><div class="character-name"><span>ช่องที่ ${index + 1}</span><strong>${escapeHtml(slot.name || 'รออัปโหลดภาพ')}</strong></div>${slot.image ? `<button class="remove-button" data-remove="${index}">×</button>` : ''}</div>`).join(''); document.querySelectorAll('[data-upload]').forEach((button) => button.addEventListener('click', () => chooseImage(Number(button.dataset.upload)))); document.querySelectorAll('[data-remove]').forEach((button) => button.addEventListener('click', () => { state.slots[Number(button.dataset.remove)].image = ''; state.slots[Number(button.dataset.remove)].name = ''; saveState(); render(); }));
}
function chooseImage(index) { if (!state.spinning) { state.selectedSlot = index; $('fileInput').click(); } }
function handleFile(event) { const file = event.target.files[0]; if (!file) return; if (!file.type.startsWith('image/') || file.size > 8 * 1024 * 1024) { alert('กรุณาเลือกภาพ PNG, JPG หรือ WebP ขนาดไม่เกิน 8 MB'); event.target.value = ''; return; } const reader = new FileReader(); reader.onload = () => { state.slots[state.selectedSlot].image = reader.result; state.slots[state.selectedSlot].name = file.name.replace(/\.[^.]+$/, ''); saveState(); render(); }; reader.readAsDataURL(file); event.target.value = ''; }
function changeSlots(value) { const count = Math.min(24, Math.max(2, Number(value))); if (count < state.slots.length && state.slots.slice(count).some((slot) => slot.image) && !confirm('ช่องท้ายที่มีภาพจะถูกลบ ต้องการลดจำนวนช่องหรือไม่?')) return; const old = state.slots; state.slots = Array.from({ length: count }, (_, index) => newSlot(old[index])); saveState(); render(); }
function playTick() { if (state.muted) return; try { const Context = window.AudioContext || window.webkitAudioContext; audioContext ||= new Context(); const oscillator = audioContext.createOscillator(); const gain = audioContext.createGain(); oscillator.frequency.value = 620; gain.gain.setValueAtTime(.04, audioContext.currentTime); gain.gain.exponentialRampToValueAtTime(.001, audioContext.currentTime + .06); oscillator.connect(gain).connect(audioContext.destination); oscillator.start(); oscillator.stop(audioContext.currentTime + .06); } catch (_) {} }
function spin() { if (!ready() || state.spinning) return; const count = state.slots.length; const segment = 360 / count; const winnerIndex = Math.floor(Math.random() * count); const target = winnerIndex * segment + segment / 2; const current = ((state.rotation % 360) + 360) % 360; state.spinning = true; state.rotation += state.rounds * 360 + (360 - target) - current + (Math.random() - .5) * segment * .55; render(); setTimeout(() => { state.spinning = false; playTick(); $('winnerImage').src = state.slots[winnerIndex].image; $('winnerName').textContent = state.slots[winnerIndex].name || 'ตัวละครผู้โชคดี'; $('winnerBackdrop').hidden = false; render(); }, 5600); }
function closeModal(which) { $(`${which}Backdrop`).hidden = true; }
function renderRound() { $('roundCount').value = state.rounds; $('roundCountValue').textContent = state.rounds; $('roundCountLabel').textContent = `${state.rounds} รอบ`; saveState(); }
document.addEventListener('DOMContentLoaded', async () => {
  state.slots = Array.from({ length: 6 }, () => newSlot()); try { const saved = await loadState(); if (saved) { state.slots = Array.from({ length: saved.slots?.length || 6 }, (_, index) => newSlot(saved.slots?.[index])); state.rounds = saved.rounds || 5; state.muted = Boolean(saved.muted); } } catch (_) {}
  $('slotCount').addEventListener('input', (event) => changeSlots(event.target.value)); $('slotMinus').addEventListener('click', () => changeSlots(state.slots.length - 1)); $('slotPlus').addEventListener('click', () => changeSlots(state.slots.length + 1)); $('roundCount').addEventListener('input', (event) => { state.rounds = Number(event.target.value); renderRound(); }); $('roundMinus').addEventListener('click', () => { state.rounds = Math.max(1, state.rounds - 1); renderRound(); }); $('roundPlus').addEventListener('click', () => { state.rounds = Math.min(20, state.rounds + 1); renderRound(); }); $('fileInput').addEventListener('change', handleFile); $('uploadButton').addEventListener('click', () => chooseImage(Math.max(0, state.slots.findIndex((slot) => !slot.image)))); $('spinButton').addEventListener('click', spin); $('clearButton').addEventListener('click', () => { if (confirm('ต้องการล้างภาพตัวละครทั้งหมดใช่ไหม?')) { state.slots.forEach((slot) => { slot.image = ''; slot.name = ''; }); saveState(); render(); } }); $('soundToggle').addEventListener('click', () => { state.muted = !state.muted; $('soundToggle').textContent = state.muted ? '♩' : '♬'; saveState(); }); $('helpButton').addEventListener('click', () => $('helpBackdrop').hidden = false); $('againButton').addEventListener('click', () => { closeModal('winner'); setTimeout(spin, 120); }); document.querySelectorAll('[data-close]').forEach((button) => button.addEventListener('click', () => closeModal(button.dataset.close))); document.querySelectorAll('.modal-backdrop').forEach((backdrop) => backdrop.addEventListener('click', (event) => { if (event.target === backdrop) backdrop.hidden = true; })); render(); renderRound();
});
